server:
  port: 8000
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: dev
  redis:
    host: brushmon-redis-dev.nu36ue.0001.apn2.cache.amazonaws.com
    password:
    port: 6379
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

logging.level:
  org.springframework:
    boot: info
    web: info